/* PRIORITY 28 */

/* GET SWITCHES */
@FMT(CMP,@WIZGET(INSTALL_TYPE)=2,'®WIZCLR(LOC_SUBSAMPLE)','®WIZSET(LOC_SUBSAMPLE=®dbHot(Samples.ini,[SWITCHES]LOC_SUBSAMPLE))');
@FMT(CMP,'@WIZGET(LOC_SUBSAMPLE)=','®WIZCLR(LOC_SUBSAMPLE)®WIZRPL(INSTALL_RESULT=4)');

/* CANNOT SET SWITCHES IN SILENT MODE */
@FMT(CMP,@WIZGET(INSTALL_SILENT)<1,'®WIZCLR(INSTALL_RESULT)');
@FMT(CMP,@WIZGET(INSTALL_SILENT)>=@WIZGET(INSTALL_RESULT),'®WIZCLR(INSTALL_RESULT)','®FMT(CHR,27)');

@WIZINIT;
@WIZMENU(LOC_SUBSAMPLE=Select installation type?,
xStore Server=LOC_xStore,
Host=LOC_Host,
Store back-office=LOC_Back);
@WIZDISPLAY;

/* INSTALL */
@FMT(CMP,@WIZGET(INSTALL_TYPE)>=2,'®TOOLS(INSTALL_SUB,Samples\@WIZGET(INSTALL_OPTION)\@WIZGET(LOC_SUBSAMPLE)\FirstLoad\,@WIZGET(LOC_SUBSAMPLE))');
@TOOLS(INSTALL_SUB,Samples\@WIZGET(INSTALL_OPTION)\@WIZGET(LOC_SUBSAMPLE)\,@WIZGET(LOC_SUBSAMPLE));

/* EXECUTED ONLY WHEN THE OPTION IS INSTALLED */
@FMT(CMP,@WIZGET(INSTALL_STEP)<3,'®FMT(CHR,26)');

/* APPEND DIFFERENT INTERFACE */
@WIZRPL(Samples.ini[SWITCHES]LOC_SUBSAMPLE=@WIZGET(LOC_SUBSAMPLE));
@DBHOT(Samples.ini,SET,Samples.ini[*);
