@WIZRPL(System.ini[TRS]SsmLevel1=TRS_CLT_WEB);

@WIZRPL(SYSTEM.INI[ECHECKOUT]TentativeMode=);
@WIZRPL(SYSTEM.INI[ECHECKOUT]MaxSkipBagging=);
@WIZRPL(SYSTEM.INI[ECHECKOUT]MaxIdleTimeError=);
@WIZRPL(SYSTEM.INI[ECHECKOUT]MaxIdleTimeAssist=);
@WIZRPL(SYSTEM.INI[ECHECKOUT]MaxTimeToPutItmOnScale=);
@WIZRPL(SYSTEM.INI[ECHECKOUT]MaxTimeToRemoveItmEOT=);
@WIZRPL(SYSTEM.INI[ECHECKOUT]MaxOwnBagWeight=);
@WIZRPL(SYSTEM.INI[ECHECKOUT]SecurityItemToleranceOver=);
@WIZRPL(SYSTEM.INI[ECHECKOUT]SecurityItemToleranceUnder=);
@WIZRPL(SYSTEM.INI[ECHECKOUT]SecurityScaleToleranceOver=);
@WIZRPL(SYSTEM.INI[ECHECKOUT]SecurityScaleToleranceUnder=);
@WIZRPL(SYSTEM.INI[ECHECKOUT]SecurityBagTolerance=);
@WIZRPL(SYSTEM.INI[ECHECKOUT]AssistedAgeVerification=1);
@WIZRPL(SYSTEM.INI[ECHECKOUT]AssistedTentative=1);

@WIZRPL(SYSTEM.INI[TRS]AutoManagerLogout=0);
@WIZRPL(SYSTEM.INI[CLIENT]AgeEntryMethod=2);

@DBHOT(SYSTEM.INI,SET,SYSTEM.INI[*);
